spring.application.name=twitter-api
server.port=3000

spring.datasource.url=jdbc:postgresql://localhost:5432/twitter_api
spring.datasource.username=postgres
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

app.jwt.secret=workintech-twitter-api-secret-key-minimum-32-characters
app.jwt.expiration-ms=86400000
